"""Resolve `image-query:` placeholders in Slidev markdown to real Unsplash URLs.

Run BEFORE `slidev export`. The renderer wrapper (`renderer/render.sh`) calls
this as its preprocessor so decks generated by the teacher OR the finetuned
student both become renderable.

Recognized patterns (in slide frontmatter YAML):
    image-query: "natural language description"
    image-query: 'single-quoted form'
    image-query: unquoted text until end of line

Each match is rewritten to:
    image: <real_url>   # from Unsplash API or the curated bank

Also scans for inline `image-query://<text>` URIs inside markdown body —
useful if the model emits them mid-content — and rewrites to the real URL.
"""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

from pipeline.tools.image_search import image_search

# image-query: "foo"   |   image-query: 'foo'   |   image-query: bare text
_FRONTMATTER_RE = re.compile(
    r"""^(\s*)image-query:\s*(?:"([^"]+)"|'([^']+)'|(.+?))\s*$""",
    re.MULTILINE,
)

# inline URI in body markdown: image-query://diverse engineering team
_INLINE_URI_RE = re.compile(r"""image-query://([^\s\)"']+)""")


def resolve(markdown: str) -> tuple[str, list[tuple[str, str]]]:
    """Return (rewritten_markdown, list_of_(query, url)_pairs)."""
    subs: list[tuple[str, str]] = []

    def _sub_frontmatter(m: re.Match[str]) -> str:
        indent = m.group(1) or ""
        query = (m.group(2) or m.group(3) or m.group(4) or "").strip()
        if not query:
            return m.group(0)
        result = image_search(query)
        subs.append((query, result.url))
        return f"{indent}image: {result.url}"

    def _sub_inline(m: re.Match[str]) -> str:
        query = m.group(1).replace("+", " ").replace("%20", " ")
        result = image_search(query)
        subs.append((query, result.url))
        return result.url

    out = _FRONTMATTER_RE.sub(_sub_frontmatter, markdown)
    out = _INLINE_URI_RE.sub(_sub_inline, out)
    return out, subs


def main() -> None:
    p = argparse.ArgumentParser()
    p.add_argument("input", type=Path, help="input Slidev .md")
    p.add_argument(
        "-o",
        "--output",
        type=Path,
        default=None,
        help="output path (default: print to stdout)",
    )
    p.add_argument(
        "--report",
        action="store_true",
        help="print the list of (query → url) substitutions to stderr",
    )
    args = p.parse_args()

    src = args.input.read_text(encoding="utf-8")
    out, subs = resolve(src)

    if args.report:
        for q, u in subs:
            print(f"  {q!r:60s} → {u}", file=sys.stderr)
        print(f"  ({len(subs)} substitutions)", file=sys.stderr)

    if args.output:
        args.output.write_text(out, encoding="utf-8")
    else:
        sys.stdout.write(out)


if __name__ == "__main__":
    main()
